apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-pass-uploads-pvc
  namespace: photo-pass
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-pass-processed-pvc
  namespace: photo-pass
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
